### ISSUE TITLE
Support collection operations

### ISSUE THREAD

**Issue by clue** [reactphp/promise-timer#15]
What is the recommended way to wait for a timeout of _multiple_ promises?

react/promise provides several promise collection primitives, which all have valid use cases.

One might assume the following is the way to go:

``` php
$promises = array(
    accessSomeRemoteResource(),
    accessSomeRemoteResource(),
    accessSomeRemoteResource()
);

$promise = \React\Promise\all($promises);

Timer\timeout($promise, 10, $loop)->then(function ($values) {
    // *all* promises resolved
});
```

How does this cope with cancellation support? (Refs #9 and #3)

**Comment by clue** [comment]
The above example is also part of the documentation (#14). However, it does currently not describe how *cancellation* of promise collections works.

**Comment by jsor** [comment]
Cancellation of promise collections should be handled within react/promise but is currently not supported. Calling cancel() on the promise returned by all/any/some etc. could be forwarded to all promises of the collection.

**Comment by clue** [comment]
> Cancellation of promise collections should be handled within react/promise but is currently not supported. 

Thanks the feedback! I've just filed https://github.com/reactphp/promise/issues/33 to keep track of this.

**Comment by clue** [comment]
In the meantime, we *might* consider adding helper functions like `timeoutAll($promises)` etc.?

**Comment by jsor** [comment]
I think we should better invest the time to implement this cleanly in react/promise. Will look at it in the next week.

**Comment by jsor** [comment]
See reactphp/promise#36

**Comment by clue** [comment]
I agree that it makes more sense to keep relying on promise primitives instead of duplicating similar logic here :+1: 

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
