### ISSUE TITLE
Consider supporting foreign promises

### ISSUE THREAD

**Issue by clue** [reactphp/promise-timer#19]
> Originally suggested by @jsor in https://github.com/reactphp/promise-timer/pull/18#issuecomment-188188717.

Likely depends on https://github.com/reactphp/promise/issues/45

**Comment by jsor** [comment]
[v2.4.0](https://github.com/reactphp/promise/releases/tag/v2.4.0) is released with support for foreign thenables.

**Comment by clue** [comment]
I agree that it makes more sense to keep relying on promises instead of duplicating similar logic here :+1: 

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
