### ISSUE TITLE
Consider moving to React namespace

### ISSUE THREAD

**Issue by clue** [reactphp/promise-timer#2]

**Comment by jsor** [comment]
+1 for moving under the React namespace

**Comment by clue** [comment]
Suggested package name would be "react/promise-timer"

Depends on #11 (and indirectly #10).

**Comment by WyriHaximus** [comment]
+1 for moving this under `react/promise-timer`

**Comment by clue** [comment]
Ideally, I'd like to move this as-is, so that it retains all tickets etc.

However, I can only move repositories to organizations that I'm the admin of. Instead of asking for admin access to the reactphp organization, I would suggest moving this to @cboden first so that he can then move this to the reactphp organization.

**Comment by clue** [comment]
Ping @cboden, what's you take on this? :)

**Comment by clue** [comment]
> Repository transfer to cboden requested

Ping @cboden, now it's up to you :)

**Comment by cboden** [comment]
The request expired. I can move it today if you make another one.

**Comment by cboden** [comment]
Repo transferred

**Comment by clue** [comment]
Awesome! :tada:

**Comment by clue** [comment]
The namespace / composer package name has to be updated before this can be closed :)
