### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by sm2017** [reactphp/promise-timer#22]
I read the source of promise-timer , I see that for each timer we have a ```addTimer``` , I am working on a project with huge request , about 10M/s 

I want to know If we have 10M timer , Is this impact performance? 
Is it better that we have a timer that manager all 10M request , I don't need accuracy , for me 3 or 4 sec for timer is not important

Do you have any better idea?

**Comment by clue** [comment]
> I want to know If we have 10M timer , Is this impact performance?

Yes, 10M timers are bound to be slower than no timers :-) Now seriously, I don't really see what we could do here. I'd suggest running some benchmarks to see if 10M/s is a reasonable number in the first place and then check to see how much overhead timeouts actually add. *IF* timeouts add some significant overhead for your particular use case and you don't need this accuracy, you may want to build a custom function that starts a single timer for multiple promises.

I'd love to see you report back and file this as a PR :shipit: :+1: 

I hope this helps :+1:
