### ISSUE TITLE
Timer seems to be not working..

### ISSUE THREAD

**Issue by Radostin** [reactphp/promise-timer#29]
Hello,

I've been trying to use your package, however, I do seem to be unable to set it up properly.

To start with, here's my setup:
```
 ~ php -v
PHP 7.1.8 (cli) (built: Aug 25 2017 10:11:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Composer.lock contents:
```
...
"name": "react/promise-timer",
"version": "v1.2.0",
...
```

Here's a code example:

```php
$loop = \React\EventLoop\Factory::create();

$promise = new Promise(function ($resolve, $reject) {
    $seconds = 10;
    sleep($seconds);
    $resolve("Unexpected Behavior.. Should've thrown an exception..");
}, function ($resolve, $reject) {
    $reject(new \Exception());
});

timeout($promise, 5, $loop)->then(function ($value) {
    die(var_dump($value));
})->otherwise(function (Exception $exception) {
    die(var_dump('Expected behavior..'));
});
```

The output:
```
string(53) "Unexpected Behavior.. Should've thrown an exception.."
```

From my understanding, I should've received the "Expected behavior.." string as a result..

Am I doing anything wrong?

Thank you in advance,
Rad

**Comment by jsor** [comment]
The `sleep()` call blocks the whole process including the loop. So, once you pass the promise to `timeout()`, it's already resolved.

If you want to the Promise to resolve in  10 seconds, you have to do that in a timer:

```php
$loop->addTimer($seconds, function() use ($resolve) {
    $resolve("Unexpected Behavior.. Should've thrown an exception..");
});
```

**Comment by Radostin** [comment]
@jsor, thank you for your reply!

I don't want to have the promise resolved in 10 seconds. Maybe my next example would illustrate in better what do I need.

```php
$loop = \React\EventLoop\Factory::create();

$promise = new Promise(function ($resolve, $reject) {
    $uri = 'http://fakeresponse.dev/?sleep=10&data={"message":"Unexpected behavior."}';
    $data = json_decode(file_get_contents($uri));
    $resolve($data->message);
}, function ($resolve, $reject) {
    $reject(new \Exception());
});

$seconds = 5;
timeout($promise, $seconds, $loop)->then(function ($value) {
    die(var_dump($value));
})->otherwise(function (Exception $exception) {
    die(var_dump('Expected behavior..'));
});
```

Basically, the FakeResponse.dev will sleep for 10 seconds before it returns the json.However, the second argument of the timeout function sets 5 seconds expected time for the resolution of the promise. Hence, exceeding the 5 seconds should throw an exception. 

From my understanding I should be getting the "Expected behavior" string.

However, I still do get the:
```
string(20) "Unexpected behavior."
```

Anyway, I am aware that I could use Guzzle/Curl timeout functionality. However, in my real-life project I am not going to be doing straight-up http requests, thus, I need something like this project.

Am I doing everything as it is supposed to?

**Comment by jsor** [comment]
As i said, you're blocking everything with `sleep()` (and `file_get_contents()` in your second example). So, you're _reaching_ the `timeout()` call only after `sleep()` has blocked the whole process 10 seconds. 

```php
sleep($seconds); // <-- That line block the process for 10 seconds
```

When working with asynchronous code like in ReactPHP, you must ensure that **everything** is non-blocking. `sleep()`and `file_get_contents()`are not. If you want to do non-blocking I/O, like HTTP requests, you must use a library which supports that, eg. https://github.com/clue/php-buzz-react.

**Comment by Radostin** [comment]
Thank you for your help. I've hoped that this will work no matter the circumstances (blocking or non-blocking function calls).
