### ISSUE TITLE
Psalm in combination with v1.8.0

### ISSUE THREAD

**Issue by gdejong** [reactphp/promise-timer#53]
Hi,

Since the recent `v1.8.0` release I am having some problems with [Psalm](https://psalm.dev/).

There is an example listed in the README of this project:

```
Or if you're using react/promise v2.2.0 or up:

React\Promise\Timer\timeout($promise, 10.0)
    ->then(function ($value) {
        // the operation finished within 10.0 seconds
    })
    ->otherwise(function (React\Promise\Timer\TimeoutException $error) {
        // the operation has failed due to a timeout
    })
    ->otherwise(function ($error) {
        // the input operation has failed due to some other error
    })
;
```

However when running Psalm with errorLevel 5 or lower I get:

```
ERROR: UndefinedInterfaceMethod - Method React\Promise\PromiseInterface::otherwise does not exist (see https://psalm.dev/181)
            ->otherwise(function (\React\Promise\Timer\TimeoutException $error) {
```

I guess this is caused by the return type hint of `PromiseInterface` that was added to `\React\Promise\Timer\timeout`.

This `timeout()` function is returning a `new Promise()`, would it be an idea to change the docblock to `@return Promise` or `@return ExtendedPromiseInterface`?

**Comment by gdejong** [comment]
@clue Can I please get your opinion on this? Thank you!

**Comment by SimonFrings** [comment]
Hey @gdejong, thanks for bringing this up :+1:

I just looked into [react/promise#202](https://github.com/reactphp/promise/pull/202), this addresses a similar topic. I think the answer for this ticket would be the same as in there. This is also something that regards promise v2, this won't be a thing in the new v3. We're not sure  when v3 will be released, but we're certain that this will come in the nearer future.

What are your thoughts on this?

**Comment by gdejong** [comment]
For me to most important thing would be to get Psalm working/happy again at a strict level. I could understand if you won't fix this for v2 since you are working on v3. I am curious, are you testing v3 in projects that use Psalm to statically analyze the code? Because that would be great in my opinion :)

**Comment by SimonFrings** [comment]
Funny coincidence, @WyriHaximus opened up an discussion in [psalm#7559](https://github.com/vimeo/psalm/discussions/7559) a week ago. To quote @WyriHaximus: "we want to make sure that  promises are type safe in both Psalm's and PHPStan's eyes".
This goes hand in hand with reactphp/promise#188.

That said, this shouldn't be a problem anymore when talking about promise v3 which is the development version at this moment (development but stable ^^). We don't have psalm integrated inside the ReactPHP projects itself, but we're using ReactPHP in some other projects in combination with psalm.

If you want to try this out you can always install the current `dev-master`, I hope this helps and gives you some insights in our plans :)

**Comment by clue** [comment]
What @SimonFrings says :+1:

@gdejong Thanks for reporting, I think we all agree that type safety is definitely super useful and something we're working on with https://github.com/reactphp/promise/pull/188 and https://github.com/reactphp/promise/pull/202, so I don't think there's much that can or needs to be done here.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Comment by WyriHaximus** [comment]
I'll upgrade that example with the `sleep` method from this package 😄
